const parts = [
    [
        [
            '"How u fly?" "Must has nitro"',
            'Mathcat, no!',
            'Don\'t make me use...',
            'Github!',
            'Perks!',
            'Now...',
            'You die',
            'Or do I?'
        ],
        [
            '',
            'Math.',
            'Skeet.',
            'Follow. Much to discuss.',
            'w...wait...',
            '',
            '+1M',
            '',
            ''
        ],
        [
            'It\'s been years since mathcat vanished.',
            'Without purpose, ginger turrned evil',
            'Silence!',
            '',
            '',
            '',
            'à² _à² ',
            'à² _à² ',
            'uh oh',
            'a mod',
            ':(',
            '',
            '',
            ''
        ],
        [
            'Something\'s wrong',
            '@@lyxal',
            'G\'joink',
            'Where did you see your friidge last?',
            'At your MOMs!!!',
            '...',
            'Canadian CIA',
            '"Mom!" "Hyper!"',
            'If you need your friend\'s fridge...',
            '',
            'It\'s over there',
            'CIA'
        ],
        [
            'You can\'t do this',
            'It\'s too late, skeet.',
            'With 1M rep and Nitro...',
            'I am unstoppable',
            'I am staff',
            'And you? Nothing.'
        ],
        [
            'So much wheat...',
            '@Wheat Wizard?',
            'Yo.',
            'Your diamond!',
            'Mathcat stole mine...',
            'And JoKing joined him.',
            '"As did I" "Frick"',
            'Pow',
            'Pow',
            'You know what happens when you FGITW',
            'You get golfed.'
        ]
    ],
    [
        [
            'Golfers',
            'Today, we face a threat',
            'Mathcat is amassing power',
            'Who will stand with me?',
            'Not us',
            'Just kidding',
            'Mathcat took our mods',
            'Mathcat took APL',
            'Mathcat took lyxal',
            'I\'m right here',
            'I think I might know how to find them',
            'There it is',
            'The castle of TID'
        ],
        [
            'owo',
            'What\'s this?',
            'What\'s this?',
            'Ginger?',
            'How did you survive the nuke?',
            'Hid in lyxal\'s fridge',
            'I\'m speechless',
            'No, you\'re joking',
            'I joined mathcat to end your reign of terror',
            'Mathcat\'s alive?!?',
            'Y\'know...',
            'I\'m sorry for the tyranny',
            'No worries, perks corrupt anyone',
            'From now on, I vow to use them for good.',
            'CIA',
            'CIA',
            '',
            'You can fly?',
            'Up to 1 hr / day',
            'I know where mathcat is',
            'Not too far, I hope',
            'Gotta land soon',
            '',
            '',
            '',
            '',
        ],
        [
            '',
            '',
            '',
            'incomprehensible',
            '?',
            'A tin can and string... clever.',
            'I am caird',
            'WW and bagel...',
            'They\'re dead',
            'I took WW\'s gun',
            'And diamond',
            'But not before he shot bagel.',
            '(who was in disguise)'
        ],
        [
            '',
            'a moat',
            'Can you do an Orion?',
            'Not without a diamond',
            'I might be able to help',
            'caird!',
            '',
            '',
            ''
        ],
        [
            'Who\'s online?',
            'Pxeger Redwolf Fmbalbuena Dlosc user wezl',
            'Spam!',
            'ugh',
            'We need our mods back',
            'We should go find them',
            'No! HN told us to stay',
            'But caird didn\'t',
            'SPAAAA!',
            'I\'m with DLosc',
            'You can stay if you want',
            'Fine',
            'Everyone agrees. NP: SPAM!'
        ],
        [
            '',
            'No choice but to go in',
            'Nice hat',
            'You too',
            'Greetings, golfers',
            'Mathcat was never here',
            'I set a trap',
            'If I lured HN and JoKing here...',
            'Mathcat would follow',
            'And I could nuke us all',
            '',
            '11ium bomb, 20MTon'
        ]
    ],
    [
        [
            'It\'ll be weeks',
            'How\'s the food situation?',
            'Not good',
            'Mathcat: "Where\'s the bakery?"',
            'You have 10s. GingerBot: Pushed 2 words',
            'POW',
            '',
            'LAND HO!',
            'Kinda rude...',
            'Land uh... y\'all',
            'nice landing',
            'Where\'s Lyxal\'s house? Follow me.',
            '',
            'DLosc: I\'ll blow the door. NP: SPAM!',
            '',
            'I\'ll go in',
            '',
            'The elevator power was cut by redwolf',
            '17',
            '(floor 11) this is Lyxal\'s floor',
            'Wzl, kick the door in',
            '',
            'His fridge is gone!',
            'It was summoned by a mod',
            'A talking plat?',
            'Yes I am emanresu A',
            'And I\'m Aaron',
            'I\'ve tracked the fridge to Canada with Scala',
            'Well let\'s go!',
            '',
        ]
    ]
]