const parts = [
    [
        [
            'Person: How u fly? \nPerson: Must has nitro',
            'Ginger: Mathcat, no!',
            'Ginger: Don\'t make me use...',
            'Github!',
            'Perks!',
            'Ginger: Now...',
            'You die',
            'Mathcat: Or do I?'
        ],
        [
            '',
            'Skeet: Math.',
            'Mathcat: Skeet.',
            'Skeet: Follow. Much to discuss.',
            'Skeet: w...wait...',
            '<mathcat vaporises skeet>',
            '+1M reputation',
            '<portal opens>',
            '<mathcat disappears>'
        ],
        [
            'Person: It\'s been years since mathcat vanished.',
            'Person: Without purpose, ginger turrned evil',
            'Ginger: Silence!',
            '<force blast>',
            '<person vanishes>',
            '<portal opens>',
            'Ginger: ಠ_ಠ',
            'ಠ_ಠ',
            'Ginger: uh oh',
            'a mod',
            '<mod nukes ginger>',
            '<ginger hides in fridge>',
            '<portal opens>',
            '<mod leaves>'
        ],
        [
            'Hyper: Something\'s wrong',
            'Hyper: @@lyxal',
            'Lyxal: G\'joink',
            'Hyper: Where did you see your friidge last?',
            'Lyxal: At your MOMs!!!',
            'Hyper: ...',
            '<lyxal and hyper go to Canadian CIA>',
            'Hyper: Mom!\nHyper\'s Mom: Hyper!',
            'Hyper\'s Mom: If you need your friend\'s fridge...',
            '<gestures at nuclear blast crater>',
            'Hyper\'s Mom: It\'s over there',
            ''
        ],
        [
            'Skeet: You can\'t do this',
            'Mathcat: It\'s too late, skeet.',
            'Mathcat: With 1M rep and Nitro...',
            'I am unstoppable',
            'I am staff',
            'And you? Nothing.'
        ],
        [
            'Bagel (disguised as Hyper): So much wheat...',
            'Bagel: @Wheat Wizard?',
            'Wheat Wizard: Yo.',
            'Bagel: Your diamond!',
            'Bagel (disguised as Hyper): Mathcat stole mine...',
            'Bagel:And JoKing joined him.',
            'WW: As did I\nBagel: Frick',
            '<ww shoots bagle>',
            '<bagel dies>',
            'Caird: You know what happens when you FGITW',
            'Caird: You get golfed.\n<shoots WW, steals diamond>'
        ]
    ],
    [
        [
            'Hyper: Golfers',
            'Hyper: Today, we face a threat',
            'Hyper: Mathcat is amassing power',
            'Hyper: Who will stand with me?',
            'Golfers: Not us',
            'Golfers: Just kidding',
            'Pygamer: Mathcat took our mods',
            'Adám: Mathcat took APL',
            'thejonymyster: Mathcat took lyxal',
            'Lyxal: I\'m right here',
            'Hyper: I think I might know how to find them',
            '<goes to castle> \nHyper: There it is',
            'Hyper: The castle of TIO'
        ],
        [
            'Jo King: owo',
            'Jo King: What\'s this?',
            '<fridge opens>',
            'Jo King: Ginger?',
            'How did you survive the nuke?',
            'Ginger: Hid in lyxal\'s fridge',
            'Jo King: I\'m speechless',
            'Ginger: No, you\'re joking',
            'Jo King: I joined mathcat to end your reign of terror',
            'Ginger: Mathcat\'s alive?!?',
            'Ginger: Y\'know...',
            'Ginger: I\'m sorry for the tyranny',
            'Jo King: No worries, perks corrupt anyone',
            'Ginger: From now on, I vow to use them for good.',
            '<shot of canadian CIA>',
            '<two red streaks fly past>',
            '<ginger and jo king flying>',
            'Jo King: You can fly?',
            'Ginger: Up to 1 hr / day',
            'Jo King: I know where mathcat is',
            'Ginger: Not too far, I hope',
            'Ginger: Gotta land soon',
            '<caird in front of castle>',
            '<caird standing by dead bodies>',
            '<caird walks towards castle>',
            '<caird looks up at castle>',
        ],
        [
            '<caird in front of castle>',
            '<ginger appears>',
            '<jo king appears>',
            'Caird: incomprehensible',
            'Jo King: ?',
            'Jo King: A tin can and string... clever.',
            'Caird: I am caird',
            'Caird: WW and bagel...',
            'They\'re dead',
            'I took WW\'s gun',
            'And diamond',
            'But not before he shot bagel.',
            '(who was in disguise)'
        ],
        [
            '<golfers in front of moat>',
            'Hyper: a moat',
            'Lyxal: Can you do an Orion?',
            'Hyper: Not without a diamond',
            'Caird: I might be able to help',
            'Adám: caird!',
            '<ginger prepares spell>',
            '<ginger casts spell>',
            '<red wall appears>'
        ],
        [
            'Bubbler: Who\'s online?',
            '<names: pxeger redwolf fmbalbuena dlosc user wzl>',
            'New Posts: Spam!',
            'Bubbler: ugh',
            'Bubbler: We need our mods back',
            'DLosc: We should go find them',
            'Redwolf: No! HN told us to stay',
            'wzl: But caird didn\'t',
            'New Posts: SPAAAA!',
            'Fmbalbuena: I\'m with DLosc',
            'You can stay if you want',
            'Redwolf: Fine',
            '<everyone agrees>\n NP: SPAM!'
        ],
        [
            '<golfers at castle gate>',
            'Hyper: No choice but to go in',
            'Caird: Nice hat',
            'Hyper: You too',
            'Skeet: Greetings, golfers',
            'Skeet: Mathcat was never here',
            'Skeet: I set a trap',
            'If I lured HN and JoKing here...',
            'Mathcat would follow',
            'And I could nuke us all',
            '<castle in cage>',
            '<bomb: 11ium bomb, 20MTon>'
        ]
    ],
    [
        [
            'Bubbler: It\'ll be weeks',
            'pxeger: How\'s the food situation?',
            'DLosc: Not good',
            'Mathcat: Where\'s the bakery?',
            'Mathcat: You have 10 seconds.\n GingerBot: Pushed 2 words',
            '<mathcat shoots gingerbot>',
            '<gingerbot dies>',
            'user: LAND HO!',
            'Redwolf: Kinda rude...',
            'wzl: Land uh... y\'all',
            'Bubbler: nice landing',
            'Bubbler: Where\'s Lyxal\'s house? \n user: Follow me.',
            '<newcastle skyline>',
            'DLosc: I\'ll blow the door.\n NP: SPAM!',
            '<door blows up>',
            'user: I\'ll go in',
            '<user, bubbler and wzl falling>',
            'wzl: The elevator power was cut by redwolf',
            '<floor 17>',
            '<floor 11>\n Bubbler: this is Lyxal\'s floor',
            'Bubbler: wzl, kick the door in',
            '<wzl kicks door open>',
            'wzl: His fridge is gone!',
            'emanresu A: It was summoned by a mod',
            'Bubbler: A talking plat?',
            'emanresu A: Yes I am emanresu A',
            'Aaron: And I\'m Aaron',
            'user: I\'ve tracked the fridge to Canada with Scala',
            'wzl: Well let\'s go!',
            '<tnbers on roof>',
        ],
        [
            'Long ago...',
            '<se nitro on pedastal> \n Helper: Finally!',
            'Helper: We have found it',
            'Mathcat: No...',
            'Helper: wha-',
            'Mathcat: I have found it \n <shoots helper>',
            '<inserts money>',
            '<machine accepts money>',
            '<machine clicks>',
            'Machine: Thanks for your purchase',
            '<mathcat leaves cave>',
            '<mathcat casts spell>',
            '<mathcat destroys cave>',
            '<mathcat leaves>',
            '<hyper standing on cliff next to city>',
            '<mathcat casts spell>',
            '<mathcat destroys city>',
            'Mathcat: So, hyper...',
            'Mathcat: Are you with me or against me?',
            'Hyper: What did you do?!',
            'Mathcat: Against? Alright...',
            'Mathcat: Your diamond...',
            'Hyper: NO',
            '<mathcat prepares spell>',
            '<mathcat steals diamond>',
            'Mathcat: Stay in your own domain, hyper',
            'Mathcat: We wouldn\'t want this getting... ugly',
            'Mathcat: This is ͟m͟y͟ stack now'
        ],
        [
            '2 years later...',
            'Ginger: Mathcat. Is he dead?',
            'Colonel: In hiding, best as we can tell',
            'Ginger: Thank you, colonel',
            'Ginger: Take your troops to Code Review.',
            'Colonel: Will do. It\'s ours within the week.',
            '<city with artillery and fires> \n Ginger: Spread the word. This is why you do not resist my control!',
            'I will find mathcat if I need to burn down every site in the network',
            'Ginger: His empire shall fall to me.',
            'Shortly after...',
            'Mathcat: You\'ve been mantaining the fridge?',
            'Jo King: Indeed. At no low risk, of course',
            'Mathcat: You know what to do, Jo',
            'Jo King: I do, sir',
            '<portal opens>',
            '<mathcat vanishes>'
        ]
    ]
]