const parts = [
    [ // s1
        [ // p1
            [
                'Person: How u fly? \nPerson: Must has nitro',
                'Ginger: Mathcat, no!',
                'Ginger: Don\'t make me use...',
                'Github!',
                'Perks!',
                'Ginger: Now...',
                'You die',
                'Mathcat: Or do I?'
            ],
            [
                '',
                'Skeet: Math.',
                'Mathcat: Skeet.',
                'Skeet: Follow. Much to discuss.',
                'Skeet: w...wait...',
                '<mathcat vaporises skeet>',
                '+1M reputation',
                '<portal opens>',
                '<mathcat disappears>'
            ],
            [
                'Person: It\'s been years since mathcat vanished.',
                'Person: Without purpose, ginger turrned evil',
                'Ginger: Silence!',
                '<force blast>',
                '<person vanishes>',
                '<portal opens>',
                'Ginger: ಠ_ಠ',
                'ಠ_ಠ',
                'Ginger: uh oh',
                'a mod',
                '<mod nukes ginger>',
                '<ginger hides in fridge>',
                '<portal opens>',
                '<mod leaves>'
            ],
            [
                'Hyper: Something\'s wrong',
                'Hyper: @@lyxal',
                'Lyxal: G\'joink',
                'Hyper: Where did you see your friidge last?',
                'Lyxal: At your MOMs!!!',
                'Hyper: ...',
                '<lyxal and hyper go to Canadian CIA>',
                'Hyper: Mom!\nHyper\'s Mom: Hyper!',
                'Hyper\'s Mom: If you need your friend\'s fridge...',
                '<gestures at nuclear blast crater>',
                'Hyper\'s Mom: It\'s over there',
                ''
            ],
            [
                'Skeet: You can\'t do this',
                'Mathcat: It\'s too late, skeet.',
                'Mathcat: With 1M rep and Nitro...',
                'I am unstoppable',
                'I am staff',
                'And you? Nothing.'
            ],
            [
                'Bagel (disguised as Hyper): So much wheat...',
                'Bagel: @Wheat Wizard?',
                'Wheat Wizard: Yo.',
                'Bagel: Your diamond!',
                'Bagel (disguised as Hyper): Mathcat stole mine...',
                'Bagel:And JoKing joined him.',
                'WW: As did I\nBagel: Frick',
                '<ww shoots bagle>',
                '<bagel dies>',
                'Caird: You know what happens when you FGITW',
                'Caird: You get golfed.\n<shoots WW, steals diamond>'
            ]
        ],
        [ // p2
            [
                'Hyper: Golfers',
                'Hyper: Today, we face a threat',
                'Hyper: Mathcat is amassing power',
                'Hyper: Who will stand with me?',
                'Golfers: Not us',
                'Golfers: Just kidding',
                'Pygamer: Mathcat took our mods',
                'Adám: Mathcat took APL',
                'thejonymyster: Mathcat took lyxal',
                'Lyxal: I\'m right here',
                'Hyper: I think I might know how to find them',
                '<goes to castle> \nHyper: There it is',
                'Hyper: The castle of TIO'
            ],
            [
                'Jo King: owo',
                'Jo King: What\'s this?',
                '<fridge opens>',
                'Jo King: Ginger?',
                'How did you survive the nuke?',
                'Ginger: Hid in lyxal\'s fridge',
                'Jo King: I\'m speechless',
                'Ginger: No, you\'re joking',
                'Jo King: I joined mathcat to end your reign of terror',
                'Ginger: Mathcat\'s alive?!?',
                'Ginger: Y\'know...',
                'Ginger: I\'m sorry for the tyranny',
                'Jo King: No worries, perks corrupt anyone',
                'Ginger: From now on, I vow to use them for good.',
                '<shot of canadian CIA>',
                '<two red streaks fly past>',
                '<ginger and jo king flying>',
                'Jo King: You can fly?',
                'Ginger: Up to 1 hr / day',
                'Jo King: I know where mathcat is',
                'Ginger: Not too far, I hope',
                'Ginger: Gotta land soon',
                '<caird in front of castle>',
                '<caird standing by dead bodies>',
                '<caird walks towards castle>',
                '<caird looks up at castle>',
            ],
            [
                '<caird in front of castle>',
                '<ginger appears>',
                '<jo king appears>',
                'Caird: incomprehensible',
                'Jo King: ?',
                'Jo King: A tin can and string... clever.',
                'Caird: I am caird',
                'Caird: WW and bagel...',
                'They\'re dead',
                'I took WW\'s gun',
                'And diamond',
                'But not before he shot bagel.',
                '(who was in disguise)'
            ],
            [
                '<golfers in front of moat>',
                'Hyper: a moat',
                'Lyxal: Can you do an Orion?',
                'Hyper: Not without a diamond',
                'Caird: I might be able to help',
                'Adám: caird!',
                '<ginger prepares spell>',
                '<ginger casts spell>',
                '<red wall appears>'
            ],
            [
                'Bubbler: Who\'s online?',
                '<names: pxeger redwolf fmbalbuena dlosc user wzl>',
                'New Posts: Spam!',
                'Bubbler: ugh',
                'Bubbler: We need our mods back',
                'DLosc: We should go find them',
                'Redwolf: No! HN told us to stay',
                'wzl: But caird didn\'t',
                'New Posts: SPAAAA!',
                'Fmbalbuena: I\'m with DLosc',
                'You can stay if you want',
                'Redwolf: Fine',
                '<everyone agrees>\n NP: SPAM!'
            ],
            [
                '<golfers at castle gate>',
                'Hyper: No choice but to go in',
                'Caird: Nice hat',
                'Hyper: You too',
                'Skeet: Greetings, golfers',
                'Skeet: Mathcat was never here',
                'Skeet: I set a trap',
                'If I lured HN and JoKing here...',
                'Mathcat would follow',
                'And I could nuke us all',
                '<castle in cage>',
                '<bomb: 11ium bomb, 20MTon>'
            ]
        ],
        [ // p3
            [ // c1
                'Bubbler: It\'ll be weeks',
                'pxeger: How\'s the food situation?',
                'DLosc: Not good',
                'Mathcat: Where\'s the bakery?',
                'Mathcat: You have 10 seconds.\n GingerBot: Pushed 2 words',
                '<mathcat shoots gingerbot>',
                '<gingerbot dies>',
                'user: LAND HO!',
                'Redwolf: Kinda rude...',
                'wzl: Land uh... y\'all',
                'Bubbler: nice landing',
                'Bubbler: Where\'s Lyxal\'s house? \n user: Follow me.',
                '<newcastle skyline>',
                'DLosc: I\'ll blow the door.\n NP: SPAM!',
                '<door blows up>',
                'user: I\'ll go in',
                '<user, bubbler and wzl falling>',
                'wzl: The elevator power was cut by redwolf',
                '<floor 17>',
                '<floor 11>\n Bubbler: this is Lyxal\'s floor',
                'Bubbler: wzl, kick the door in',
                '<wzl kicks door open>',
                'wzl: His fridge is gone!',
                'emanresu A: It was summoned by a mod',
                'Bubbler: A talking plat?',
                'emanresu A: Yes I am emanresu A',
                'Aaron: And I\'m Aaron',
                'user: I\'ve tracked the fridge to Canada with Scala',
                'wzl: Well let\'s go!',
                '<tnbers on roof>',
            ],
            [ // c2
                'Long ago...',
                '<se nitro on pedastal> \n Helper: Finally!',
                'Helper: We have found it',
                'Mathcat: No...',
                'Helper: wha-',
                'Mathcat: I have found it \n <shoots helper>',
                '<inserts money>',
                '<machine accepts money>',
                '<machine clicks>',
                'Machine: Thanks for your purchase',
                '<mathcat leaves cave>',
                '<mathcat casts spell>',
                '<mathcat destroys cave>',
                '<mathcat leaves>',
                '<hyper standing on cliff next to city>',
                '<mathcat casts spell>',
                '<mathcat destroys city>',
                'Mathcat: So, hyper...',
                'Mathcat: Are you with me or against me?',
                'Hyper: What did you do?!',
                'Mathcat: Against? Alright...',
                'Mathcat: Your diamond...',
                'Hyper: NO',
                '<mathcat prepares spell>',
                '<mathcat steals diamond>',
                'Mathcat: Stay in your own domain, hyper',
                'Mathcat: We wouldn\'t want this getting... ugly',
                'Mathcat: This is ͟m͟y͟ stack now'
            ],
            [ // c3
                '2 years later...',
                'Ginger: Mathcat. Is he dead?',
                'Colonel: In hiding, best as we can tell',
                'Ginger: Thank you, colonel',
                'Ginger: Take your troops to Code Review.',
                'Colonel: Will do. It\'s ours within the week.',
                '<city with artillery and fires> \n Ginger: Spread the word. This is why you do not resist my control!',
                'I will find mathcat if I need to burn down every site in the network',
                'Ginger: His empire shall fall to me.',
                'Shortly after...',
                'Mathcat: You\'ve been mantaining the fridge?',
                'Jo King: Indeed. At no low risk, of course',
                'Mathcat: You know what to do, Jo',
                'Jo King: I do, sir',
                '<portal opens>',
                '<mathcat vanishes>'
            ],
            [ // c4
                'Redwolf: So, do y\'all have any ideas on how we\'re getting to Canada?',
                'DLosc: Ontario, specifically',
                'emanresu A: Y\'all arrived on a ship, right?',
                'Redwolf: Yeah, but I uh...',
                'pxeger: Redwolf\'s kinda shit at ship navigation',
                'Anyway, any way we can get a new boat?',
                'Aaron: What about the bakery?',
                'Redwolf: What about it?',
                'Aaron: It\'s how Lyxal got around',
                'wzl: Ooh... with the side bar?',
                'Aaron: Yeah! Side warping',
                'Bubbler: Well where\'s the bakery?',
                'emanresu A: Sydney. I can show y\'all the way!',
                'wzl: Nice! \n Bubbler: Alright, let\'s do it \n DLosc:  Woooo',
                '<new posts walking to sydney with TNBers on back>\nNew Posts: SPAAAM! SPAAAM!',
            ],
            [ // c5
                'pxeger: Wait, stop the feed!',
                'New Posts: ::unwrap() \n <gingerbot lying in pool of hydraulic fluid>',
                'pxeger: Looks like a bot',
                'Bubbler: Looks like a hydraulic leak',
                '<bubbler samples hydraulic fluid>',
                'Bubbler: DLosc, can you find a match for this fluid?',
                'DLosc: I\'m on it',
                '<dlosc standing by chemistry table> \n DLosc: Aha!',
                'DLosc: Your mysteryfluidhas turned out to be BX-1201, an industrial solvent and hydraulic oil',
                'Well, your sample was actually A471, a similar solvent Redwolf never uses',
                'This BX-1201 came from NP\'s resrve fluid bladder',
                '<bubbler laughs>',
                'DLosc: Yes yes, it\'s very funny',
                'Now let\'s get this bot moving, and get back to chat',
                '<DLosc pours the BX-1201 into GingerBot>',
                'GingerBot: Hiya!',
                'GingerBot: Word "mathcat" contains illegal letters',
                'Bubbler: wha-',
                'GingerBot: Pushing word "staff"',
                'GingerBot: Ping of GingerIndustries Pi is 20ms',
                'GingerBot: Biya!',
                '<gingerbot disappears>',
                'pxeger: But... ginger\'s dead!',
                'DLosc: Mathcat... staff?',
                'Bubbler: We really need to get back to Canada',
                'Bubbler: I don\'t think we have the full story',
                '<tnbers at the bakery> \n Bubbler: Well, here we are',
            ],
            [ // c6
                '<Castle of TIO within cage>',
                'Hyper: Jo King!',
                'caird: We\'ve been tricked',
                "Jo King: Where's mathcat?",
                "Hyper: Not here. Skeet lured us, as bait for him",
                "Jo King: Bait?",
                "Adám: To kill him. All of us, actually. 11ium.",
                "Ginger: I fell right into his trap...",
                "Hyper: So did I.",
                "caird: Skeet seems to have fled. Probably a tunnel out.",
                "lyxal: What do you say we break into teams?",
                "Adám: Caird, Hyper, Jony, find the bomb",
                "Adám: Lyxal, Jo King, hat guy, look for an escape",
                "Ginger: I'll assist y'all with perks",
                "Adám: And I'll find APL",
                "lyxal: Sounds good to me",
                "Hat guy: We still need to find lyxal!",
                "Hyper: I don't even know who this hat guy is",
                "<both groups are gathered in the great hall>",
                "caird: Well, see y'all soon",
                "Jo King, lyxal, and hat guy: o/",
                "Hat guy (revealed to be a Sʨɠɠan): Sʨɠɠan, do you copy?; Sʨɠɠan (aboard New Posts): I copy. En route to Bakery. Bot squealed but plan is a-go"
            ],
            [ // c7
                "Fmbalbuena: Well, how do we sidechannel?",
                "<TNB user 1>: You in any other rooms, Fmbalbuena?",
                "Fmbalbuena: No...",
                "<TNB user 2>: NP prolly is",
                "<room freezes>",
                "<TNB user 2>: wtf...",
                "Bubbler: The room just froze",
                "<sockpuppets appear>",
                "sockpuppets: KILL",
                "Redwolf: Sockpuppets. Run!",
                "<-2 hit points>",
                "<sock gets kicked>",
                "<this won't end well>",
                "CRUNCH <socks get their heads smashed together>",
                "Bzzzt <sock saws at TNBer>",
                "<-2 hit points three times>",
                "<sock gets punched by a squeamish TNBer>",
                "POW POW POW <sock shoots at a TNBer>",
                "<TNBer drops to the floor to dodge bullets>",
                "<TNBer uses their momentum to do a flip toward the sock>",
                "<TNBer grabs gun from sock>",
                "POW <TNBer punches sock>",
                "<TNBer holds socks at gunpoint>",
                "PTPTPTPTPTPTPT <DLosc shoots using New Posts, in the form of \"NP 7.62\", a machine gun>",
                "PTPTPTPTPTPTPT <DLosc shoots at some socks using New Posts, in the form of \"NP 7.62\", a machine gun>",
                "Bubbler: Nice work, guys",
                "<TNB user 1>: That machine gun's brilliant, DLosc",
                "<TNB user 2>: WATCH OUT!",
                "<icicles fall>",
                "<TNB user 1>: They've stopped falling!",
                "Ginger: Teleportation. Twice a month.",
                "<silence>",
                "<TNB user 1>: So, about that warp...",
                "Wzl: I'm in TNB still. o/ <waving goodbye>",
                "<Wzl warps away>",
                "<Wzl walks around in their bio>",
                "<Wzl places a ladder to get to the bakery in their bio>",
                "Wzl: @pxeger @Redwolf @Fmbalbuena @DLosc @NewPosts @Bubber @user",
                "<TNB users in unison>: Yay! Woo! :D"
            ],
            [ // c8
                "Sʨɠɠan: Good morning, your kingship",
                "mathcat: Morning to you too, Sʨɠɠan",
                "Sʨɠɠan: Hyper and Jo are at TIO castle",
                "Sʨɠɠan: They, and some TNB noobs, are locked in with an 11ium bomb",
                "mathcat: Thank you, spymaster. Order the socks to ready for battle.",
                "PyGamer0: This door should take us to the top of the keep",
                "Hyper: Can I borrow your diamond, caird?",
                "caird: Sure",
                "POW <Hyper kicks door down>",
                "caird: Why did you need my diamond to kick the door down...",
                "Hyper: Why not lol",
                "Jo King: The walkway's collapsed, lyxal",
                "lyxal: No worries, I got this",
                "lyxal: I run a bit of an...organization",
                "<Jo King, lyxal, and thejonymyster cross the bridge of limbs>"
            ],
            [ // c9
                "Adám: APL!",
                "Jon Skeet: Not so fast, Adám",
                "Jon Skeet: If you don't call off the hunt for my 11ium bomb...",
                "Adám: No! You can't!",
                "Adám: {(A×⌈(⍴⍵,1)÷A←⍴⍺)⍴⍺} ; <attribution for APL code from post ID 243968, CC-BY-SA 4.0 by Fmbalbuena>",
                "Jon Skeet: What?",
                "<APL grows into a giant>",
                "Jon Skeet: uh oh",
                "<APL kicks Jon Skeet in his face>",
                "POW POW POW <Jon Skeet shoots at APL's leg>",
                "Adám: Any last words, Skeet?",
                "Jon Skeet: Nice golfing language",
                "Adám: That's it, finish him"
            ],
            [ // c10
                "Hyper: Well, any success?",
                "lyxal: Nope, no way out",
                "Adám: Can confirm, Skeet was still here",
                "Adám: ...but is no longer a factor",
                "caird: I may know a way out of this place",
                "caird: A security hole in TIO's sandboxing",
                "Jo King: Awesome! Let's do it!",
                "caird: So, y'all will go into this vsock. You will float around in the Digital Ocean for some time.",
                "caird: I will shoot the 11ium bomb, destroying the castle and its fortifications. You will then return.",
                "lyxal: Wait but...won't you die?",
                "caird: Yes. But it is our only option. Hyper, take this diamond.",
                "Hyper: caird, we will never forget you",
                "lyxal: Bye, caird",
                "caird: Goodbye, lyxal",
                "<gun rigged to remote denonator antenna, pointing at 11ium bomb>",
                "user, appearing out of nowhere: Wait!",
                "Aaron, in user's hand: We've got another way",
                "user: This is a sock",
                "user: I can command it to push the button.",
                "caird: user, you're a genius!",
                "user: Push the button in 10s <10 seconds>; sock: YES",
                "BOOOM",
                "<mathcat and a sock army can now be seen on a hill behind the castle's rubble>",
                "<TNB RO>: uh oh"
            ]
        ],
        [ // p4
            [ // c1
                "<Hyper and Jo King are in a rural location>",
                "Hyper: I built this complex years ago",
                "Hyper: Nitro was too OP, and with no promise it was truly missing...",
                "Hyper: Anyway, these supplies should give the Exchange Resistance a fighting chance",
                "Hyper: 20,028 socks, a spare crystal, and 110 flags",
                "Hyper: All the food our guys will need for a brutal winter sabotage campaign",
                "Hyper: mathcat won't stand a chance, and caird's in TNB rallying support",
                "Hyper: By next week...<sees mathcat> OH NO",
                "mathcat: Good to see you again, hyper",
                "Hyper: Jo King, run!",
                "Jo King (to mathcat): Sir, I've retrived the revolutionary",
                "mathcat: Lock him in the domain. Secure the crystal in Orion.",
                "Jo King: Copy, will do",
                "Hyper: No prison will stop justice",
                "Jo King: If you had done what was suggested to you, you wouldn't be in this situation"
            ],
            [ // c2
                "caird: So, Jo King, why so blurry?",
                "Jo King: Radiation. It'll wear off soon.",
                "user: Land y'all!",
                "<a steep cliff is spotted>",
                "Hyper: What is this place?",
                "caird: Ancient ruins. This MySpace plugin has a backdoor that'll take us right outside the castle",
                "<TNB user>: AAAAAA <as they fall down the backdoor pit>; caird: No choice but to jump",
                "<everybody's out of the digital ocean, now on a grassy hill>",
                "socks: KILL CRUSH STOMP; PyGamer0: uh...guys?",
                "<two -2s from sockpuppet saw blade attack>",
                "<-100 from sockpuppet armored vehicle redflagging Jo King>",
                "lyxal: Back! Back! <brandishing sword at sockpuppets>",
                "Hyper: Run!; Adám: There's nowhere _to_ run!",
                "Ginger: git pull --force",
                "<red portals appear under the distressed golfers>",
                "Ginger: <checks box> assist y'all with perks",
                "Adám: Thanks, Ginger"
            ],
            [ // c3
                "<Exchange Resistance>",
                "caird: This should be a nice safe room to regroup in",
                "PyGamer0: I had no clue this place was still accessible. WIndows Phone isn't even a subdomain anymore.",
                "Bubbler: Ginger, there's someone you might want to see",
                "GingerBot: Gingyr!",
                "Ginger: :D",
                "pxeger: So, any ideas for where to go from here?",
                "Jo King: Hyper, you should probably tell them",
                "Hyper: Prior to Jo King's infiltration-; Jo King: Sorry! :p; Hyper: -I brought a spare crystal to the Resistance supply bunker",
                "user: Crystal?",
                "Hyper: A diamond which hadn't been charged. An empty vehicle.",
                "caird: This was an unusual crystal. It was apparently too...corruptible.",
                "Hyper: Its undictic <not a real word> absorbitivity was 2.0",
                "caird: ...so it could absorb the power from nearby mods",
                "Ginger: Where is this crystal?",
                "Hyper: Fort Orion",
                "Jo King: An outpost high above Physics. An abandoned particle collider.",
                "thejonymyster: Well let's go!"
            ],
            [ // c4
                "<TNB user>: How on earth are we supposed to break into THAT?",
                "Hyper: Follow me",
                "<Sign with Physics Stack logo and \"Orion Collider Project: North Collider\" under it>",
                "<Dark rail tunnel with \"Orion North\" sign>",
                "<In minecart> <TNB user>: I see something up ahead",
                "<Bubbler, Jo King, a TNB user holding Aaron, Lyxal, and caird have dismounted>",
                "<Looking at a map lebeled \"Orion Complex Security\"> emanresu A: It's probably in storage",
                "<TNB user>: What do you see? <The gang are sneaking up stairs into a security control room, and Aaron is being held up to see what's in there>",
                "Aaron: One security guy, facing away",
                "Bubbler: Let's go!",
                "Bubbler: That one! <points at a building>",
                "<Orion Storage Facility>",
                "<four clicks, from caird shooting a silenced gun at two guards by the door>",
                "caird: Hurry!",
                "Hat guy: Glad I brought my lockpicks",
                "Adam: It's inside that box",
                "TheJonyMyster: Got it!",
                "caird: Let's get out of here",
                "<The gang are standing on a platform, with Hyper standing next to lyxal's fridge below it>",
                "Jo King <with Hyper now on the platform>: Time for the OTHER Project Orion",
                "<The fridge nuke explodes, destroying the Orion facility and launching the gang into the sky aboard the platform>"
            ]
        ]
    ]
]
